# Generated by Django 4.0.4 on 2022-05-28 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contct',
            name='phone',
            field=models.CharField(max_length=100),
        ),
    ]
