# Generated by Django 4.0.4 on 2022-05-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contct_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contct',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
