# Generated by Django 3.2.9 on 2022-05-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_contct_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contct',
            name='phone',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
