# Generated by Django 3.2.9 on 2022-05-28 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contct_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contct',
        ),
    ]
