# Generated by Django 3.2.9 on 2022-05-28 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_contct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contct',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='contct',
            name='phone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
