# Generated by Django 4.0.4 on 2022-05-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220528_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contct',
            name='name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='contct',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
